### ISSUE TITLE
I am getting an error on the pip version in termux

### ISSUE THREAD

**Issue by KdntNinja** [Hackertrackersj/Tbomb#16]
~ $ tbomb
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/tbomb", line 5, in <module>
    from tbomb.bomber import main
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/tbomb/bomber.py", line 13, in <module>
    from pkg_resources import resource_string
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by dhruvsolanki2188** [comment]
Same here
